site_name: CentralCorp Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Basculer en mode sombre
    - scheme: slate
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Basculer en mode clair
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  language: fr
# Configuration multilingue
plugins:
  - i18n:
      default_language: fr
      languages:
        en: English
        fr: Français
      nav_translations:
        en:
          - Home: index.md
          - Prerequisites: prerequis.md
          - Step 1 - GitHub Setup: step1.md
          - Step 2 - Global Configuration: step2.md
          - Step 3 - Panel Installation: step3.md
          - Step 4 - Panel Configuration: step4.md
          - Step 5 - Final Steps: step5.md
        fr:
          - Accueil: index.md
          - Prérequis: prerequis.md
          - Étape 1 - Configuration GitHub: step1.md
          - Étape 2 - Configuration Globale: step2.md
          - Étape 3 - Installation du Panel: step3.md
          - Étape 4 - Configuration du Panel: step4.md
          - Étape 5 - Étapes Finales: step5.md
      redirect_to: fr

# Extensions Markdown améliorées
markdown_extensions:
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins pour des fonctionnalités supplémentaires
plugins:
  - search
  - tags