site_name: " "
theme:
  name: material
  logo: assets/img/logo.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Basculer en mode sombre
    - scheme: slate
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Basculer en mode clair
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  language: fr
# Extensions Markdown améliorées
markdown_extensions:
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins pour des fonctionnalités supplémentaires
plugins:
  - search
  - tags
copyright: CentralCorp is not affiliated with Mojang or Azuriom.

extra:
  alternate:
    - name: 🇬🇧 English
      link: /en/ 
      lang: en
    - name: 🇫🇷 Français
      link: /fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CentralCorp
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
